server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweetmart9
    username: postgres
    password: sweetmart
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update     

